name: ansi_styles
description: ANSI escape codes for styling strings in the terminal.
version: 0.3.2
homepage: https://github.com/invertase/dart-cli-utilities/tree/main/packages/ansi_styles

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.5
